framework:
    default_locale: '%env(APP_DEFAULT_LOCALE)%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%env(APP_DEFAULT_LOCALE)%'
